// [number of languages][number of texts][max. length of text]

const char myLanguage[3][45][50] = {
  { "English",
    "Rotary direction changed",
    "Please release button",
    "Screen flipped",
    "Calibrate analog meter",
    "Release button when ready",
    "encoder set to optical",
    "encoder set to standard",
    "FM/AM receiver",
    "Tuner: !None!",
    "Volume:",
    "Converter:",
    "Low bandedge:",
    "High bandedge:",
    "RF Level offset:",
    "Stereo threshold:",
    "High Cut corner:",
    "Highcut threshold:",
    "Low level threshold:",
    "Contrast:",
    "Set volume",
    "Set converter offset",
    "Set low bandedge",
    "Set high bandedge",
    "Set level offset",
    "Set Stereo sep. threshold",
    "Set high cut corner frequency",
    "Set High cut threshold",
    "Set low level threshold",
    "Set Display brightness",
    "Off",
    "Screen is muted!",
    "To unmute uncheck RF+ box",
    "OFF",
    "SCANNING...",
    "Tuner not detected",
    "Tuner version set: v",
    "Please restart tuner",
    "Show RDS errors",
    "Language",
    "Choose language",
    "PRESS MODE TO EXIT AND STORE",
	"On",
	"Softmute FM",
	"Softmute AM"
  },
  
  { "Nederlands",
    "Rotary richting aangepast",
    "Laat aub de knop los",
    "Scherm gedraaid",
    "Kalibratie analoge meter",
    "Laat knop los indien gereed",
    "encoder ingesteld als optisch",
    "encoder ingesteld als standaard",
    "FM/AM ontvanger",
    "Tuner: !Geen!",
    "Volume:",
    "Converter:",
    "Lage bandgrens:",
    "Hoge bandgrens:",
    "RF niveau afwijking:",
    "Stereo grens:",
    "Hoge tonen afval:",
    "Hoog afval grens:",
    "Laag signaal grens:",
    "Helderheid:",
    "Stel volume in",
    "Stel converter afwijking in",
    "Stel ondergrens in",
    "Stel bovengrens in",
    "Stel signaal afwijking in",
    "Stel stereo grens in ",
    "Stel hoge tonen afval in",
    "Stel hoge tonen grens in",
    "Stel laag signaal grens in",
    "Stel helderheid in",
    "Uit",
    "Scherm is bevroren!",
    "Schakel RF+ uit om weer te activeren",
    "UIT",
    "ZOEKEN...",
    "Tuner niet herkend!",
    "Tuner versie ingesteld: v",
    "Herstart de tuner",
    "Toon RDS fouten",
    "Taal",
    "Kies taal",
    "DRUK OP MODE OM AF TE SLUITEN",
	"Aan",
	"Ruisonderdrukking FM",
	"Ruisonderdrukking AM"
  },
  { "Polski", 
   "Kierunek obrotu zmieniony", 
   "Zwolnij przycisk", 
   "Obrocono ekran", 
   "Kalibracja analogowego miernika", 
   "Zwolnij przycisk gdy gotowe", 
   "wybrano enkoder optyczny", 
   "wybrano standardowy enkoder", 
   "Odbiornik FM/AM", 
   "Tuner: !Brak!", 
   "Glosnosc:", 
   "Konwerter:", 
   "Dolna granica pasma:", 
   "Gorna granica pasma:", 
   "Odchylenie poziomu RF:", 
   "Prog Stereo:", 
   "Krawedz dolnoprzep..:", 
   "Prog dolnoprzepust.:", 
   "Prog niskiego sygnalu:", 
   "Kontrast:", 
   "Ustaw glosnosc", 
   "Ustaw odchylenie konwertera", 
   "Ustaw dolna granice pasma", 
   "Ustaw gorna granice pasma", 
   "Ustaw odchylenie sygnalu", 
   "Ustaw prog separacji Stereo", 
   "Czest. gran. filtra dolnoprzep.", 
   "Ustaw prog dolnoprzep.", 
   "Ustaw dolna granice sygnalu", 
   "Ustaw jasnosc wyswietlacza", 
   "Wyl.", 
   "Ekran jest wyciszony!", 
   "Aby wyl. wyciszenie odznacz RF+", 
   "WYL.", 
   "SKANOWANIE...", 
   "Nie wykryto tunera", 
   "Ustawiono wersje tunera: v", 
   "Prosze uruchomic pon. tuner", 
   "Pokaz bledy RDS", 
   "Jezyk", 
   "Wybierz swoj jezyk",
   "WCISNIJ MODE ABY ZAMKNAC I ZAPISAC",
   "On", 										// Needs translation!
   "Softmute FM",								// Needs translation!
   "Softmute AM" 								// Needs translation!
   }


};
